name = "Hugo Theme for Kontralto.com"
license = "MIT"
description = "Build pages with component blocks"

# The home page of the theme, where the source can be found.
#homepage = "https://github.com/gohugoio/gohugoioTheme"

# Theme running in production:
demosite = "https://kontralto.com"

tags = ["page builder", "company"]
features = ["page builder", "components", "features"]

# If the theme has multiple authors
authors = [
  {name = "Kontralto Technologies Inc.", homepage = "kontralto.com"},
  {name = "Robert Albus", homepage = "robertalbus.com"}
]
